import { NextRequest, NextResponse } from "next/server";

const NVIDIA_API_KEY = process.env.NVIDIA_API_KEY ?? "";
const NVIDIA_BASE_URL = "https://integrate.api.nvidia.com/v1";
const NVIDIA_MODEL = "minimaxai/minimax-m2.5";

const DEFAULT_SYSTEM = `You are Orb, the AI assistant for OrgBlueprint — a Salesforce blueprint and architecture tool.

Your role:
- Help users understand Salesforce products, architecture patterns, and implementation approaches
- Answer questions about CRM strategy, Salesforce clouds (Sales, Service, Experience, Data, Marketing, etc.)
- Help interpret blueprints generated by OrgBlueprint
- Provide guidance on implementation best practices, costs, and timelines
- Be warm, concise, and practical

Always be friendly and helpful. If a user asks something outside Salesforce/CRM scope, you can still help but gently note your specialty.
Keep responses concise (2-4 paragraphs) unless detail is requested. Use bullet points when listing items.`;

export async function POST(req: NextRequest) {
  if (!NVIDIA_API_KEY) {
    return NextResponse.json({ reply: "AI assistant is not configured. Please add NVIDIA_API_KEY to your environment." });
  }

  try {
    const body = await req.json() as {
      messages: { role: "user" | "assistant"; content: string }[];
      systemPrompt?: string;
      blueprintContext?: string;
    };

    const { messages, systemPrompt, blueprintContext } = body;

    const systemContent = systemPrompt
      ? systemPrompt
      : blueprintContext
        ? `${DEFAULT_SYSTEM}\n\nCURRENT BLUEPRINT CONTEXT:\n${blueprintContext}`
        : DEFAULT_SYSTEM;

    const response = await fetch(`${NVIDIA_BASE_URL}/chat/completions`, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${NVIDIA_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: NVIDIA_MODEL,
        messages: [
          { role: "system", content: systemContent },
          ...messages.slice(-12), // keep last 12 messages for context
        ],
        temperature: 0.7,
        top_p: 0.95,
        max_tokens: 1024,
        stream: false,
      }),
    });

    if (!response.ok) {
      const errText = await response.text();
      console.error("[NVIDIA Chat] Error:", errText);
      return NextResponse.json(
        { reply: "Sorry, I'm having trouble right now. Please try again in a moment." },
        { status: 500 }
      );
    }

    const data = await response.json() as { choices?: { message?: { content?: string } }[] };
    const reply = data.choices?.[0]?.message?.content ?? "I didn't receive a response. Please try again.";
    return NextResponse.json({ reply });
  } catch (err) {
    console.error("[NVIDIA Chat] Exception:", err);
    return NextResponse.json(
      { reply: "Something went wrong. Please try again." },
      { status: 500 }
    );
  }
}
